version : "3.3"
services:
  web:
    image: rishikeshops/react_django_app:latest
    ports:
      - "8001:8001"
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=test@123"
